apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ${APP}
  labels:
    app: ${APP}
webhooks:
  - name: ${APP}.example.com
    clientConfig:
      service:
        name: ${APP}
        namespace: ${NAMESPACE}
        path: /mutate
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    failurePolicy: Ignore
    admissionReviewVersions:
      - v1
      - v1beta1
    sideEffects: None
    timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APP}
  name: ${APP}
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ${APP}
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP}
  name: ${APP}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP}
  template:
    metadata:
      labels:
        app: ${APP}
    spec:
      containers:
        - image: ${IMAGE}:${VERSION}
          imagePullPolicy: Always
          name: default
          volumeMounts:
            - mountPath: /etc/pki/certs
              name: volume-cert
      restartPolicy: Always
      serviceAccountName: prow-pipeline
      volumes:
        - secret:
            defaultMode: 420
            optional: false
            secretName: ${APP}-cert
          name: volume-cert

---

apiVersion: v1
data:
  cert.pem: ${CERT_PEM}
  key.pem: ${KEY_PEM}
kind: Secret
metadata:
  name: ${APP}-cert
  namespace: ${NAMESPACE}
type: Opaque
